export const aiToolsData = [
  {
    id: 201, name: "Cursor", slug: "cursor-ai-editor",
    logo: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=100&auto=format&fit=crop&q=60",
    verified: true, pricing: "freemium", website: "https://cursor.com",
    category: "Code Assistants",
    description: "AI-first code editor built on VS Code that understands entire codebases and generates context-aware code changes across multiple files.",
    features: ["Full codebase indexing and context", "Multi-file refactoring suggestions", "Integrated chat with code references"],
    useCases: ["Large-scale codebase refactoring", "Debugging complex issues", "Learning unfamiliar codebases"],
    pros: ["Best-in-class multi-file understanding", "Familiar VS Code interface", "Fast iteration speed"],
    cons: ["Higher resource usage than standard editors", "Subscription required for full features"],
    alternatives: ["Windsurf", "GitHub Copilot", "Cody"],
    tags: ["code-editor", "ai-coding", "developer-tools"],
    seoTitle: "Cursor AI Code Editor Review", seoDescription: "Cursor: AI-first code editor with codebase-wide understanding and multi-file refactoring.", canonicalUrl: "https://hotai.news/tools/cursor-ai-editor"
  },
  {
    id: 202, name: "Runway ML", slug: "runway-ml",
    logo: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=100&auto=format&fit=crop&q=60",
    verified: true, pricing: "free-trial", website: "https://runwayml.com",
    category: "Video Generators",
    description: "Professional-grade AI video generation and editing platform used by filmmakers and content creators for text-to-video, inpainting, and motion tracking.",
    features: ["Gen-3 Alpha text-to-video generation", "AI-powered video inpainting and removal", "Motion brush for precise animation control"],
    useCases: ["Film pre-visualization", "Social media content creation", "Product demo videos"],
    pros: ["Highest quality video generation available", "Professional editing tools included", "Active community and templates"],
    cons: ["Credit-based pricing adds up quickly", "Rendering times can be long for complex videos"],
    alternatives: ["Pika Labs", "Kling AI", "Sora"],
    tags: ["video-generation", "creative-ai", "filmmaking"],
    seoTitle: "Runway ML Video Generator Review", seoDescription: "Runway ML: professional AI video generation with Gen-3 Alpha for filmmakers and creators.", canonicalUrl: "https://hotai.news/tools/runway-ml"
  },
  {
    id: 203, name: "Ollama", slug: "ollama",
    logo: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=100&auto=format&fit=crop&q=60",
    verified: true, pricing: "open-source", website: "https://ollama.ai",
    category: "Developer Tools",
    description: "Run large language models locally on your machine with a single command. Supports Llama, Mistral, Gemma, and dozens of other open-weight models.",
    features: ["One-command model download and execution", "Automatic hardware optimization", "OpenAI-compatible API server"],
    useCases: ["Local AI development and testing", "Private data processing", "Offline AI applications"],
    pros: ["Completely free and open-source", "Dead simple setup process", "Excellent hardware auto-detection"],
    cons: ["Requires decent hardware for larger models", "No built-in fine-tuning support"],
    alternatives: ["LM Studio", "Jan", "llama.cpp"],
    tags: ["local-ai", "open-source", "llm-runner"],
    seoTitle: "Ollama Local LLM Runner Review", seoDescription: "Ollama: run Llama, Mistral, and other LLMs locally with a single command. Free and open-source.", canonicalUrl: "https://hotai.news/tools/ollama"
  },
  {
    id: 204, name: "Perplexity", slug: "perplexity-ai",
    logo: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=100&auto=format&fit=crop&q=60",
    verified: true, pricing: "freemium", website: "https://perplexity.ai",
    category: "Productivity",
    description: "AI-powered search engine that provides sourced, real-time answers with citations. Combines web search with language model reasoning for research tasks.",
    features: ["Real-time web search with AI synthesis", "Source citations for every claim", "Focus modes for academic, coding, and writing"],
    useCases: ["Research and fact-checking", "Market analysis", "Technical documentation lookup"],
    pros: ["Always provides source citations", "Real-time information access", "Clean distraction-free interface"],
    cons: ["Free tier has daily query limits", "Occasional source quality issues"],
    alternatives: ["Google Gemini", "You.com", "Phind"],
    tags: ["ai-search", "research", "productivity"],
    seoTitle: "Perplexity AI Search Engine Review", seoDescription: "Perplexity: AI search engine with real-time sourced answers and citations for research.", canonicalUrl: "https://hotai.news/tools/perplexity-ai"
  },
  {
    id: 205, name: "Midjourney v7", slug: "midjourney-v7",
    logo: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=100&auto=format&fit=crop&q=60",
    verified: true, pricing: "paid", website: "https://midjourney.com",
    category: "Image Generators",
    description: "Industry-leading AI image generator known for exceptional aesthetic quality, photorealistic rendering, and fine-grained style control via text prompts.",
    features: ["Photorealistic image generation", "Style reference and character consistency", "Built-in upscaling and variation tools"],
    useCases: ["Concept art and illustration", "Marketing visual assets", "Product mockup generation"],
    pros: ["Unmatched aesthetic quality", "Strong community and prompt sharing", "Consistent character generation"],
    cons: ["No free tier available", "Discord-based workflow can be clunky"],
    alternatives: ["DALL-E 3", "Stable Diffusion", "Flux"],
    tags: ["image-generation", "creative-ai", "design"],
    seoTitle: "Midjourney v7 AI Image Generator Review", seoDescription: "Midjourney v7: industry-leading AI image generation with photorealistic quality and style control.", canonicalUrl: "https://hotai.news/tools/midjourney-v7"
  },
  {
    id: 206, name: "Bolt.new", slug: "bolt-new",
    logo: "https://images.unsplash.com/photo-1504639725590-34d0984388bd?w=100&auto=format&fit=crop&q=60",
    verified: true, pricing: "freemium", website: "https://bolt.new",
    category: "Developer Tools",
    description: "Browser-based AI development environment that generates, runs, and deploys full-stack web applications from natural language descriptions.",
    features: ["Full-stack app generation from prompts", "In-browser code execution and preview", "One-click deployment to production"],
    useCases: ["Rapid prototyping", "MVP development", "Learning web development"],
    pros: ["Zero local setup required", "Incredibly fast from idea to deployed app", "Supports multiple frameworks"],
    cons: ["Complex apps may need manual refinement", "Limited backend database options"],
    alternatives: ["Replit", "v0.dev", "Lovable"],
    tags: ["web-development", "ai-builder", "no-code"],
    seoTitle: "Bolt.new AI App Builder Review", seoDescription: "Bolt.new: generate and deploy full-stack web apps from natural language in your browser.", canonicalUrl: "https://hotai.news/tools/bolt-new"
  }
];
